remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Manuela Orlas Rengifo
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: IMG_20230321_202940_995-fotor-20231016165423.jpg

